### ISSUE TITLE
Only list direct dependencies

### ISSUE THREAD

**Issue by rraziel** [mwittig/npm-license-crawler#10]
Hello,

Is there any way to only list direct dependencies? I tried --dependencies but that only removes my own project from the list.
The idea being that only the dependencies in my own package.json are listed and not those dependencies' own dependencies.
In a similar fashion, is it possible to only list dependencies without dev dependencies?

If none of those features are currently available, would a pull request help?

Thanks.

**Comment by mputters** [comment]
From a quick look at license-checker, it seems like it already supports those so it's only a matter of passing the flags.

**Comment by mwittig** [comment]
Thanks for your report. 

> From a quick look at license-checker, it seems like it already supports those so it's only a matter of passing the flags.

Which option do you think it is with `license-checker`? As far as I can see, it is not supported by the  `license-checker` command line tool.  Anyhow, I'll regard this as a feature request.

**Comment by mwittig** [comment]
> If none of those features are currently available, would a pull request help?

Contributions are welcome and appreciated, highly!

**Comment by Cederman** [comment]
+1

**Comment by mwittig** [comment]
released npm-license-crawler@0.1.6
