### ISSUE TITLE
--omitVersion removes scoped packages

### ISSUE THREAD

**Issue by thibmaek** [mwittig/npm-license-crawler#34]
Output with `./node_modules/.bin/npm-license-crawler --onlyDirectDependencies  --dependencies --production --json f.json`: 

```json
{
    "@react-native-community/netinfo@2.0.3": {
        "licenses": "MIT",
        "repository": "https://github.com/react-native-community/react-native-netinfo",
        "licenseUrl": "https://github.com/react-native-community/react-native-netinfo/raw/master/LICENSE",
        "parents": "daikin"
    },
    ...
}
```

---

Output with: `./node_modules/.bin/npm-license-crawler --onlyDirectDependencies  --dependencies --omitVersion --production --json f.json`: 

```json
{
   "": {
        "licenses": "MIT",
        "repository": "https://github.com/react-native-community/react-native-netinfo",
        "licenseUrl": "https://github.com/react-native-community/react-native-netinfo/raw/master/LICENSE",
        "parents": "daikin"
    },
    ...
}
```

**Comment by bitcrumb** [comment]
This was already fixed in this commit:
https://github.com/mwittig/npm-license-crawler/commit/c756abf730f768531318ce755176c79d768eef2f

Apparently we were using an outdated version of npm-license-crawler (0.1.9) which did not contain this fix yet. Updating fixed the issue. This can be closed.
