### ISSUE TITLE
CSV Parsing Fails in Header ( or first) Line

### ISSUE THREAD

**Issue by johnsdavis47** [mwittig/npm-license-crawler#4]
When using Text::CSV to parse the CSV file produced using the npm-license-crawler option --csv file_name option, parsing fails in the first ( or header ) line. The 4th field **License URL** is not double quoted. 

For example:

"module name","license","repository", **license URL**, "parent path"

"accept@2.1.0","BSD-3-Clause","https://github.com/hapijs/accept","https://github.com/hapijs/accept/raw/master/LICENSE","hapi:leto-app"

"align-text@0.1.4","MIT","https://github.com/jonschlinkert/align-text","https://github.com/jonschlinkert/align-text/raw/master/LICENSE","center-align:cliui:yargs:uglify-js:handlebars:leto-app"

"amdefine@1.0.0","BSD-3-Clause AND MIT","git+https://github.com/jrburke/amdefine","git+https://github.com/jrburke/amdefine/raw/master/LICENSE","source-map:handlebars:leto-app"

**Comment by mwittig** [comment]
Thanks for your bug report! I am going to fix this asap.

**Comment by mwittig** [comment]
Released npm-license-crawler@0.1.4
