### ISSUE TITLE
Allow --relativeLicensePath

### ISSUE THREAD

**Issue by timfish** [mwittig/npm-license-crawler#8]
Many thanks for `npm-license-crawler`, I'm also using it to generate output from `jspm_packages` which appears to work great.

`license-checker` has a `--relativeLicensePath` option. It would be useful so I can include the full licence text in my generated licences page.

**Comment by mwittig** [comment]
OK, sounds reasonable to me and should be difficult to implement. I'll put this on my list

**Comment by timfish** [comment]
Thanks!

**Comment by mwittig** [comment]
Released  npm-license-crawler@0.1.5. 

Please let me know if the feature suits your requirements. If you like npm-license-crawler, please consider &#x2605; starring [the project ](https://github.com/mwittig/npm-license-crawler).

**Comment by timfish** [comment]
Looks good, I'll give it a go.

**Comment by timfish** [comment]
This is great. Thanks!
